apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: testBal2
  projectName: testbuildpack
  annotations:
    componentType: service
spec:
  inbound:
    - name: testBal2
      port: 3000
      type: REST
      context: .
      schemaFilePath: openapi.yaml
